export const GET_PROJECT_REQUEST = 'GET_PROJECT_REQUEST'
export const GET_PROJECT_REQUEST_SUCCESS = 'GET_PROJECT_REQUEST_SUCCESS'
export const GET_PROJECT_REQUEST_FAIL = 'GET_PROJECT_REQUEST_FAIL'

export const GET_ALL_LOG_BY_CODE_REQUEST = 'GET_ALL_LOG_BY_CODE_REQUEST'
export const GET_ALL_LOG_BY_CODE_SUCCESS = 'GET_ALL_LOG_BY_CODE_SUCCESS'
export const GET_ALL_LOG_BY_CODE_FAIL = 'GET_ALL_LOG_BY_CODE_FAIL'

export const UPLOAD_NEW_PROJECT_REQUEST = 'UPLOAD_NEW_PROJECT_REQUEST'
export const UPLOAD_NEW_PROJECT_REQUEST_SUCCESS = 'UPLOAD_NEW_PROJECT_REQUEST_SUCCESS'
export const UPLOAD_NEW_PROJECT_REQUEST_FAIL = 'UPLOAD_NEW_PROJECT_REQUEST_FAIL'


